//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IE_Project_Final_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal_Crashes
    {
        public Nullable<double> X { get; set; }
        public Nullable<double> Y { get; set; }
        public Nullable<double> OBJECTID { get; set; }
        public string ACCIDENT_NO { get; set; }
        public string ABS_CODE { get; set; }
        public string ACCIDENT_STATUS { get; set; }
        public Nullable<System.DateTime> ACCIDENT_DATE { get; set; }
        public string ACCIDENT_TIME { get; set; }
        public string ALCOHOLTIME { get; set; }
        public string ACCIDENT_TYPE { get; set; }
        public string DAY_OF_WEEK { get; set; }
        public string DCA_CODE { get; set; }
        public string HIT_RUN_FLAG { get; set; }
        public string LIGHT_CONDITION { get; set; }
        public string POLICE_ATTEND { get; set; }
        public string ROAD_GEOMETRY { get; set; }
        public string SEVERITY { get; set; }
        public string SPEED_ZONE { get; set; }
        public string RUN_OFFROAD { get; set; }
        public Nullable<double> NODE_ID { get; set; }
        public Nullable<double> LONGITUDE { get; set; }
        public Nullable<double> LATITUDE { get; set; }
        public string NODE_TYPE { get; set; }
        public string LGA_NAME { get; set; }
        public string REGION_NAME { get; set; }
        public Nullable<double> VICGRID_X { get; set; }
        public Nullable<double> VICGRID_Y { get; set; }
        public Nullable<double> TOTAL_PERSONS { get; set; }
        public Nullable<double> INJ_OR_FATAL { get; set; }
        public Nullable<double> FATALITY { get; set; }
        public Nullable<double> SERIOUSINJURY { get; set; }
        public Nullable<double> OTHERINJURY { get; set; }
        public Nullable<double> NONINJURED { get; set; }
        public Nullable<double> MALES { get; set; }
        public Nullable<double> FEMALES { get; set; }
        public Nullable<double> BICYCLIST { get; set; }
        public Nullable<double> PASSENGER { get; set; }
        public Nullable<double> DRIVER { get; set; }
        public Nullable<double> PEDESTRIAN { get; set; }
        public Nullable<double> PILLION { get; set; }
        public Nullable<double> MOTORIST { get; set; }
        public Nullable<double> UNKNOWN { get; set; }
        public Nullable<double> PED_CYCLIST_5_12 { get; set; }
        public Nullable<double> PED_CYCLIST_13_18 { get; set; }
        public Nullable<double> OLD_PEDESTRIAN { get; set; }
        public Nullable<double> OLD_DRIVER { get; set; }
        public Nullable<double> YOUNG_DRIVER { get; set; }
        public string ALCOHOL_RELATED { get; set; }
        public Nullable<double> UNLICENCSED { get; set; }
        public Nullable<double> NO_OF_VEHICLES { get; set; }
        public Nullable<double> HEAVYVEHICLE { get; set; }
        public Nullable<double> PASSENGERVEHICLE { get; set; }
        public Nullable<double> MOTORCYCLE { get; set; }
        public Nullable<double> PUBLICVEHICLE { get; set; }
        public string DEG_URBAN_NAME { get; set; }
        public string DEG_URBAN_ALL { get; set; }
        public string LGA_NAME_ALL { get; set; }
        public string REGION_NAME_ALL { get; set; }
        public string SRNS { get; set; }
        public string SRNS_ALL { get; set; }
        public string RMA { get; set; }
        public string RMA_ALL { get; set; }
        public string DIVIDED { get; set; }
        public string DIVIDED_ALL { get; set; }
        public string STAT_DIV_NAME { get; set; }
        public int ID { get; set; }
    }
}
