//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IE_Project_Final_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class C_Total_of_species__
    {
        public string animalSubType { get; set; }
        public string animalType { get; set; }
        public string biology { get; set; }
        public string briefId { get; set; }
        public string colours { get; set; }
        public string commercial { get; set; }
        public string depths { get; set; }
        public string diet { get; set; }
        public string dietCategories { get; set; }
        public string displayTitle { get; set; }
        public string distribution { get; set; }
        public string endemicity { get; set; }
        public string generalDescription { get; set; }
        public string habitat { get; set; }
        public string habitats { get; set; }
        public string hazards { get; set; }
        public string maximumSize { get; set; }
        public string nationalParks { get; set; }
        public string plants { get; set; }
        public string taxonomy_class { get; set; }
        public string taxonomy_commonName { get; set; }
        public string taxonomy_family { get; set; }
        public string taxonomy_genus { get; set; }
        public string taxonomy_infraorder { get; set; }
        public string taxonomy_kingdom { get; set; }
        public string taxonomy_order { get; set; }
        public string taxonomy_otherCommonNames { get; set; }
        public string taxonomy_phylum { get; set; }
        public string taxonomy_species { get; set; }
        public string taxonomy_subclass { get; set; }
        public string taxonomy_subfamily { get; set; }
        public string taxonomy_subgenus { get; set; }
        public string taxonomy_suborder { get; set; }
        public string taxonomy_subphylum { get; set; }
        public string taxonomy_subspecies { get; set; }
        public string taxonomy_superclass { get; set; }
        public string taxonomy_superfamily { get; set; }
        public string taxonomy_superorder { get; set; }
        public string taxonomy_taxonName { get; set; }
        public string waterColumnLocations { get; set; }
        public string whenActive { get; set; }
        public string whereToLook { get; set; }
        public Nullable<double> yearWritten { get; set; }
        public string url { get; set; }
        public int ID { get; set; }
    }
}
