//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IE_Project_Final_WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wildlifeaidEntities1 : DbContext
    {
        public wildlifeaidEntities1()
            : base("name=wildlifeaidEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animal_Crashes> Animal_Crashes { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }

        public System.Data.Entity.DbSet<IE_Project_Final_WebApi.Models.C_Total_of_species__> C_Total_of_species__ { get; set; }
    }
}
